# Site wide configuration

title: BrewerySites
description: Web design for craft breweries, made easy.
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://localhost:4000

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Tyler Young
  email: tyler@conversioninsights.net
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: An avid home brewer with an ever-growing cellar, Tyler is the lead developer of Brewery Sites.
  avatar: Tyler-Young-160x160.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
